feat(UIcons): Create ui library with UIcons as the first components - FA-10
Satellite-im/Uplink-Mobile pull request #3
Opened 2022-04-05 12:49 UTC by lgmarchi

## Description

- Created UILibrary as package 
- Created UIcons and all related files

## Type of Change

- [ x ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ x ] 📝 Documentation
- [ ] 🗑️ Chore

2022-04-05 15:59 UTC, hyj1204 requested changes
All the Icons look good, just I have some suggestion for the structure of the project. 
1) Could your change the filename from 'all' to 'foldername.dart' / 'foldername_export.dart', like 'core.dart' or 'core_export.dart'? so we can easily tell the difference between all the all.dart files.

![image](https://user-images.githubusercontent.com/14248245/161791100-e1650bc1-68a3-4661-98db-2af8c28900f7.png)

2) Could you make examples as a new package? so we can separate examples and UI component into two package. For the production app, we only need UI components, so we can unplug the example package to reduce the app size. When we need to see the showroom, we can just add example package.

3) Could you separate counter and showroom? Leave the counter part is for testing the app to see if it is able to run functionally. Main file points to showroom by default to see all the UI components we built so far.

2022-04-05 22:10 UTC, stavares843 commented on ui_library/README.md
> +from the package authors, and more.
do we need this? seems unnecessary to have a read me for this folder

2022-04-05 22:10 UTC, stavares843 commented on ui_library/.metadata
> +project_type: package
should this be on ui_library/.gitignore?

2022-04-05 22:10 UTC, stavares843 commented on ui_library/lib/core/icons/icons.dart
> +/// Copyright (c) 2020, Lucide Contributors
do we need this commented out code?

2022-04-05 22:10 UTC, stavares843 commented on ui_library/lib/examples/icons/icons.dart
> +class UIconExample extends StatelessWidget {
is this all mock examples? based on the name - UIconExample

2022-04-05 22:10 UTC, stavares843 commented on ui_library/lib/widgets/icon/u_icon.dart
> +  /// ```
do we need this commented out code?

2022-04-05 22:10 UTC, stavares843 commented on ui_library/lib/widgets/icon/u_icon_data.dart
> +  /// All the parameters are defined in [UIcons]
do we need this commented out code?

2022-04-05 22:10 UTC, stavares843 commented on ui_library/test/ui_library_test.dart
> +
should this have anything else, besides a empty file?

2022-04-05 22:10 UTC, stavares843 commented on ui_library/test/widgets/icons/u_icons_test.dart
> +  const _kFontFam = 'UIcons';
is this name expected to be UI Icons? is somewhat a bit hard to read

2022-04-06 12:17 UTC, lgmarchi commented on ui_library/lib/core/icons/icons.dart
> +/// Copyright (c) 2020, Lucide Contributors
Sara, each comments with three bars ///, they are documentation, in this case we are mentioning the copyrights.

2022-04-06 12:18 UTC, lgmarchi commented on ui_library/lib/examples/icons/icons.dart
> +class UIconExample extends StatelessWidget {
Yes, it will be used to build a showroom, to understand better the widgets and their functionalities.

2022-04-06 12:18 UTC, lgmarchi commented on ui_library/lib/widgets/icon/u_icon.dart
> +  /// ```
This is about documentation of the widget.

2022-04-06 12:18 UTC, lgmarchi commented on ui_library/lib/widgets/icon/u_icon_data.dart
> +  /// All the parameters are defined in [UIcons]
This is about documentation of the widget.

2022-04-06 12:19 UTC, lgmarchi commented on ui_library/test/widgets/icons/u_icons_test.dart
> +  const _kFontFam = 'UIcons';
Are you asking about _kFontFam?

2022-04-06 12:37 UTC, lgmarchi commented on ui_library/README.md
> +from the package authors, and more.
It will be necessary for explain the package, in this case ui_library, the components of the uplink. What do you think?

2022-04-06 14:57 UTC, stavares843 commented on ui_library/lib/core/icons/icons.dart
> +/// Copyright (c) 2020, Lucide Contributors
and do we need that?

2022-04-06 14:58 UTC, stavares843 commented on ui_library/test/widgets/icons/u_icons_test.dart
> +  const _kFontFam = 'UIcons';
i mean the UIcons

2022-04-06 15:09 UTC, lgmarchi commented on ui_library/test/widgets/icons/u_icons_test.dart
> +  const _kFontFam = 'UIcons';
U is the name we defined to be our library components widgets, because U came from Uplink... So we have Icons class in flutter, but when we customized it for a component in Uplink, we call it UIcons.

2022-04-06 17:36 UTC, lgmarchi commented on ui_library/test/ui_library_test.dart
> +
No, we deleted this file in another commit

2022-04-06 17:59 UTC, lgmarchi commented on ui_library/.metadata
> +project_type: package
This is used by Flutter and control which channel in Flutter framework we are using. I think it is needed to check if our current app is the same version in stable channel, if not, it will warning to upgrade.

2022-04-06 18:01 UTC, lgmarchi commented on ui_library/lib/core/icons/icons.dart
> +/// Copyright (c) 2020, Lucide Contributors
Liz was searching about copyrights and where we need to mention them, i always see the copyrights in this way, maybe we can add in our terms and licenses in the future with these copyrights and delete the comments.

2022-04-06 18:07 UTC, stavares843 commented on ui_library/test/widgets/icons/u_icons_test.dart
> +  const _kFontFam = 'UIcons';
thanks for clarifying 🔨

2022-04-06 18:07 UTC, stavares843 commented on ui_library/lib/core/icons/icons.dart
> +/// Copyright (c) 2020, Lucide Contributors
thanks for clarifying 🔨

2022-04-06 18:07 UTC, stavares843 commented on ui_library/.metadata
> +project_type: package
thanks for clarifying 🔨

2022-04-06 18:08 UTC, stavares843 commented on ui_library/README.md
> +from the package authors, and more.
sounds good

2022-04-06 21:34 UTC, hyj1204 approved these changes
We did some code refactoring to make it more organizable. 

[Here](https://docs.google.com/document/d/1LgAN-7mNtgMOegeAukJ2mcphgO9G6XqoUNNdsn-N9sk/edit?usp=sharing) is the project hierarchy and name convention we used

The code looks good and shows UIcon correctly.

![image](https://user-images.githubusercontent.com/14248245/162075113-e620cdc1-954c-4390-8e4c-74ed00a25476.png)

2022-04-06 21:39 UTC, merged