test(ui-library): add coverage for UNotifications
Satellite-im/Uplink-Mobile pull request #76
Opened 2022-08-03 15:34 UTC by drepram

## Description

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🧪 Tests
- [ ] 🗑️ Chore

2022-08-03 17:58 UTC, stavares843 requested changes

2022-08-03 17:58 UTC, stavares843 commented on packages/ui_library/test/widgets/notifications/u_notifications_test.dart
> +// part 'package:ui_library/widgets/notifications/models/u_sent_link_notification.dart';
do we need this commented out? 🔨

2022-08-03 17:58 UTC, stavares843 commented on packages/ui_library/test/widgets/notifications/u_notifications_test.dart
> +      // final _UFriendRequestNotification _uNotificationCard =
do we need this commented out? 🔨

2022-08-04 02:53 UTC, drepram commented on packages/ui_library/test/widgets/notifications/u_notifications_test.dart
> +      // final _UFriendRequestNotification _uNotificationCard =
It's a work-in-progress 😄 Lucas has some ideas on how to improve this PR and I'm adding them today before this PR gets merged 😁

2022-08-04 02:53 UTC, drepram commented on packages/ui_library/test/widgets/notifications/u_notifications_test.dart
> +// part 'package:ui_library/widgets/notifications/models/u_sent_link_notification.dart';
Some of them are necessary for an upcoming fix (see other comment 😄 )

2022-08-04 11:08 UTC, stavares843 commented on packages/ui_library/test/widgets/notifications/u_notifications_test.dart
> +// part 'package:ui_library/widgets/notifications/models/u_sent_link_notification.dart';
thanks 😄

2022-08-04 11:08 UTC, stavares843 commented on packages/ui_library/test/widgets/notifications/u_notifications_test.dart
> +      // final _UFriendRequestNotification _uNotificationCard =
thanks 😄

2022-08-04 11:09 UTC, stavares843 approved these changes

2022-08-04 17:42 UTC, phillsatellite approved these changes

2022-08-05 15:14 UTC, stavares843 commented on pubspec.lock
> +    version: "43.0.0"
@lgmarchi are you ok with these updates?

2022-08-05 16:57 UTC, drepram commented on pubspec.lock
> +    version: "43.0.0"
For me, these updates were necessary because without it... my Flutter was not working :(

2022-08-05 20:39 UTC, lgmarchi approved these changes
The tests are working pretty well, and now it is possible to see some tests in a basic flow. 
![image](https://user-images.githubusercontent.com/63157656/183159180-74b46bcd-aa3b-4dd7-b2e5-0c4f43901c60.png)

https://user-images.githubusercontent.com/63157656/183159189-6d276738-80ea-42a3-946f-c7b92e2db034.mov

2022-08-05 20:39 UTC, merged